### ISSUE TITLE
Add resources to Data Science

### ISSUE THREAD

**Issue by Lagstill** [DevScript/Code-Khata#128]
Assign this to me, hence I can raise PR to include modules and basic files realted to Data Science, I have created it for Numpy,Pandas and time_series_analysis

**Comment by mursalfk** [comment]
Sure thing @Lagstill 
I am assigning you the issue. Please make sure to close the issue after the PR.

**Comment by Lagstill** [comment]
Task Completed

**Comment by mursalfk** [comment]
Great. Thanks @Lagstill 
Please don't close the issues on your own.
