### ISSUE TITLE
I want to add Learn.md to React_Js folder.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [DevScript/Code-Khata#134]
I want to add basic React JS principles (components, properties, and hooks) to Learn.md. It will help the learners to understand the basic concepts of React and how to implement them.

Kindly assign this issue to me, I'm a Hacktoberfest participant. 😊

**Comment by mafzaldev** [comment]
@KiranAminPanjwani 
You have not added any reading material for ReactJS. If you only want to contribute a project. May I contribute "Introduction to ReactJS for beginners"?
