### ISSUE TITLE
Want to add Competitive Programming by Felix Halim and Steven Halim ( one of the best books for competitive programming )

### ISSUE THREAD

**Issue by HARSHITSHARMA18** [DevScript/Code-Khata#152]
I would like to add Competitive Programming by Felix Halim and Steven Halim ( which is one of the top 5 recommended books by gfg on their list of competitive programming books )

**Comment by mursalfk** [comment]
Sure thing @HARSHITSHARMA18 
I am assining you the issue. Make sure to close the issue after you make the PR.

**Comment by HARSHITSHARMA18** [comment]
Hey @mursalfk I have made the [PR ](https://github.com/DevScript/Code-Khata/pull/153) , you can merge that
