### ISSUE TITLE
I want to make a TicTacToe application in Java.

### ISSUE THREAD

**Issue by Farrukh466** [DevScript/Code-Khata#180]
Please assign this issue to me.

**Comment by jawadkhanpk** [comment]
Hey I am experienced App Developer having 6months of industry experience, please assign me this issue so that I can start building Tic Tac Toe Game in Java. Thanks

**Comment by jawadkhanpk** [comment]
Hey I am experienced App Developer having 6months of industry experience, please assign me this issue so that I can start building Tic Tac Toe Game in Java. Thanks

**Comment by mursalfk** [comment]
HEllo. Yes sure thing
