### ISSUE TITLE
Create Low-Code Application

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#181]
## Low-Code Application/Platform
A low-code development platform provides a development environment used to create application software through a graphical user interface. A low-coded platform may produce entirely operational applications, or require additional coding for specific situations.

Learn about Low-Code Applications, and create some to participate in HacktoberFest 2022

More info at [here](https://kissflow.com/low-code/low-code-overview/)

**Comment by javeriatabassum145** [comment]
Using which tool? can we make low code app on power apps by Microsoft?

**Comment by mursalfk** [comment]
Yes. You can use any platform you like.

**Comment by javeriatabassum145** [comment]
OK assign it to me, I will make Task Management App using power apps.

**Comment by javeriatabassum145** [comment]
I have made a PR of Task Management App (Low Code). Kindly check.
