### ISSUE TITLE
Add Code for Dart

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#56]
Create a folder for Dart, add Code in the Dart folder, add some code on basic topics (like loops, conditional statements etc), Asynchronous Programming and Null Safety.

**Comment by WaniAthar** [comment]
can i work on this? @mursalfk

**Comment by Sscuber03** [comment]
can i also work on this?

**Comment by mursalfk** [comment]
Sure thing guys. I am assigning this to you guys then.
All you have to do it add meaning full code.
Remember, to participate in HacktoberFest, the code should not be spam.
