### ISSUE TITLE
⚡ Add code for JavaScript 

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#57]
Be it React, Angular, Vue.js, Next.js, or simple JavaScript.
Javascript is the heartthrob of every web developer.
Do contribute more and more in JavaScript.

**Comment by sripor62** [comment]
I want to work on this issue .Can you assign me this

**Comment by mursalfk** [comment]
Sure thing. I am assigning you this issue. Please make sure to submit QUALITY codes.

**Comment by DevAffan** [comment]
I wanna Contribute to this, hope the Codes will be useful for others.

**Comment by mursalfk** [comment]
Sure thing @DevAffan I am assinging you this issye.
