### ISSUE TITLE
Useful documents & resources 🚀 

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#59]
You can also add useful documentation and resources including
> Presentations
> Charts
> Lifecycles
> PDFs
> Coding Techniques
> Logic Building Techniques

**Comment by devgenix** [comment]
Hey, I can do this. Can you assign it to me?

**Comment by mursalfk** [comment]
Sure thing. I am assigning you this issue. Please make sure to submit QUALITY codes.
