### ISSUE TITLE
Adding Different Sorts of Algorithms

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#60]
Please add different Algorithms to the relevant languages.
Algorithms such as sorting, searching etc.

**Comment by Sscuber03** [comment]
I want to add some sorting and searching algorithms for c++, such as bubble and selection sort, quick sort, merge sort, heap sort etc. Can this be assigned to me, or should i create a different issue, which i will be assigned

**Comment by mursalfk** [comment]
Sure. I am assigning this to you then.
All you have to do it add meaning full code. 
Remember, to participate in HacktoberFest, the code should not be spam.

**Comment by sripor62** [comment]
I want to add some algorithms in C++ on the topic linked list and Tree

**Comment by mursalfk** [comment]
Sure thing. I am assigning you this issue too. Please make sure you submit QUALITY codes. Spam PRs will be marked as SPAM.

**Comment by ruchikayadav1408** [comment]
Shall i work on this?

**Comment by dhruv052001** [comment]
Please assign me this issue , i want to work on this....

**Comment by mursalfk** [comment]
Sure thing @ruchikayadav1408 @dhruv052001 
I am assigning you both this issue. Please make the PRs.

**Comment by jawadkhanpk** [comment]
Hey please assign I got some  sorting Algorithm. wana add into this repo

**Comment by mursalfk** [comment]
Sure thing @jawadkhanpk 
I am assigning you these issues. Please procees.

**Comment by mursalfk** [comment]
Also, please don't close the issue after your pull request.
Thanks

**Comment by wasibhussain** [comment]
hello mursal bhai, i also want to contribute in sorting algorithms kindly assign me.
