### ISSUE TITLE
Add resources for Machine Learning 🤖 

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#61]
Machine Learning is a vast field.
Do you think you can help us spread the knowledge?
Try it out 💯

**Comment by ShahzaibJutt** [comment]
Assign it to me.

**Comment by mursalfk** [comment]
Sure. I am assigning this to you then.
All you have to do it add meaning full code.
Remember, to participate in HacktoberFest, the code should not be spam.
