### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#62]
Making a project is like explaining the code in real life. 
Do you think you can help us spread the knowledge?
Try it out 💯

**Comment by Siddhanthota** [comment]
I can add a project. Can you assign me this?

**Comment by navanitnandakumar** [comment]
I can add a few projects
Assign?...

**Comment by mursalfk** [comment]
Sure. I am assigning you this issue. 
Please keep in mind that only QUALITY codes will be merged. Spam code will be reported.

**Comment by ShivayeModi** [comment]
@mursalfk . I can also add a project . Can you assign me this too?

**Comment by navanitnandakumar** [comment]
I can add a few projects...
Can you assign?
