### ISSUE TITLE
Python Automation Codes

### ISSUE THREAD

**Issue by mursalfk** [DevScript/Code-Khata#68]

**Comment by Prakhar9450** [comment]
can you assign it to me please

**Comment by mursalfk** [comment]
Sure thing @Prakhar9450 
I am assiging you this issue. 

Please make sure that you push quality code/documentations and don't close the issue on it's own.

**Comment by Kabir1302** [comment]
can yo please assign it to me. :)

**Comment by mursalfk** [comment]
YEs sure. @Kabir1302
