### ISSUE TITLE
Python Machine Learning Common Functions

### ISSUE THREAD

**Issue by Jolinator** [DevScript/Code-Khata#73]
I was thinking maybe it would be useful to share functions that handle data like the mean, the variation, percentile, linear regression, polynomial regression etc. that are all useful in backend machine learning.

I would be able to provide most of these if this is wanted

Thanks

**Comment by mursalfk** [comment]
Sure. Please go ahead

**Comment by mursalfk** [comment]
@Jolinator Please don't close the issues on your own.
